// Code generated by tygo. DO NOT EDIT.
// Source: internal/domain. Regenerate with `just tygo`.

//////////
// source: types.go
/*
Package domain holds the request and response types that make up the HTTP
API. It is the single source of truth for the API shape: TypeScript types
are generated from this package by tygo (see tygo.yaml).
*/

/**
 * RegisterRequest is the body of POST /api/auth/register.
 */
export interface RegisterRequest {
	email: string;
	password: string;
}
/**
 * LoginRequest is the body of POST /api/auth/login.
 */
export interface LoginRequest {
	email: string;
	password: string;
}
/**
 * UserResponse describes an authenticated user.
 */
export interface UserResponse {
	id: number /* int32 */;
	email: string;
}
/**
 * AuthResponse is returned by every endpoint that establishes or reports the
 * current session: register, login and me.
 */
export interface AuthResponse {
	user: UserResponse;
}
/**
 * MessageResponse is returned by endpoints that report an outcome with no
 * other payload, such as logout.
 */
export interface MessageResponse {
	message: string;
}
/**
 * HealthResponse is returned by GET /api/health.
 */
export interface HealthResponse {
	status: string;
}
/**
 * DashboardResponse is the example protected payload.
 */
export interface DashboardResponse {
	message: string;
	email: string;
}
/**
 * ErrorResponse is the body of every non-2xx API response.
 */
export interface ErrorResponse {
	error: string;
}
