FROM golang:1.27-alpine
RUN go install github.com/air-verse/air@latest
# Keep in step with GOOSE_VERSION in the justfile.
ARG GOOSE_VERSION=v3.28.0
RUN go install github.com/pressly/goose/v3/cmd/goose@${GOOSE_VERSION}
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
EXPOSE 8080
CMD ["sh", "-c", "goose -dir migrations postgres \"$DATABASE_URL\" up && air -c .air.toml"]
